### PR TITLE
Eluv release 4.4

### PR DESCRIPTION
**Pull request by JanFalkin**
The purpose of this pull is to capture the constituent parts that go into eluvio additions to FFmpeg.  This pull captures exactly that.  The release-4.4 branch being pulled to is merely a mirror of FFmpeg release/4.4.

### CODE REVIEW

**Comment by elv-serban** [comment]
I am attaching the patch so we can review against it:

[ffmpeg-elv-8aec7d1.patch.gz](https://github.com/qluvio/FFmpeg/files/6948390/ffmpeg-elv-8aec7d1.patch.gz)

**Comment by JanFalkin** [comment]
Adding the reject list from the application of the patch.  
[rejects.tar.gz](https://github.com/qluvio/FFmpeg/files/6948402/rejects.tar.gz)

**Comment by elv-reza** [comment]
I have updated the branch that had some missing parts. Now we can play hls clear and sample aes with this branch.

hls-aes128 still has some problems.

@elv-peter can you take a look at this? it seems that encoding init segment with aes-128 has some problem.

**Comment by elv-peter** [comment]
Some players expect the init to be clear, or dependent on the ordering in the manifest, if that's what you're referring to. We handle this with `player_profile`

**Comment by elv-peter** [comment]
I think this is a good opportunity move to a naming convention where we prefix our branches with "elv", and leave upstream branches alone. Note that this means we don't want to merge into "release-4.4", and "master" should be reverted to upstream (after cloning it to a branch to save it)

Also disable non-FF merges to prevent this mess in the future

**Comment by elv-peter** [comment]
README-ELV.md is missing

**Review by elv-peter — APPROVED** [review]

**Pull request closed without merging**
